---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: |
  https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/{{ station_id }}.json
  https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?begin_date={{ "now" | date: "%s" | minus: 86400 | date: "%Y%m%d" }}&range=192&interval=hilo&station={{ station_id }}&product=predictions&datum={{ datum }}&time_zone=gmt&units=metric&format=json
polling_headers: ''
polling_body: ''
id: 98475
custom_fields:
  - keyname: author_bio
    name: About This Plugin
    field_type: author_bio
    description: Upcoming low and high tides, provided by NOAA. On weekdays, it also highlights the upcoming weekend high tides.
    github_url: https://github.com/jbarreiros/trmnl_noaa_tides
    learn_more_url: https://github.com/jbarreiros/trmnl_noaa_tides
    email_address: johnbarreiros2@gmail.com
  - keyname: station_id
    field_type: string
    name: Station ID
    description: Find your station at <a href="https://tidesandcurrents.noaa.gov/">https://tidesandcurrents.noaa.gov/</a>
  - keyname: time_format
    field_type: select
    name: Time Format
    options:
      - 12-hour (AM/PM): 12-hour
      - 24-hour: 24-hour
    default: 12-hour
  - keyname: datum
    field_type: string
    name: Datum
    description: The default option <b>MLLW</b> represents the average of the lower low water height of each tidal day observed over the National Tidal Datum Epoch.
    default: MLLW
    help_text: See <a href="https://tidesandcurrents.noaa.gov/datum_options.html">all datums</a>.
name: Upcoming Tides (NOAA)
refresh_interval: 60
